version: 2

checks:
  file-lines:
    config:
      threshold: 750

  method-lines:
    config:
      threshold: 50

  return-statements:
    config:
      threshold: 3

  similar-code:
    config:
      threshold: 100

plugins:
  eslint:
    enabled: true
    channel: "eslint-4"
    config:
      config: "./.eslintrc.js"
      ignore_warnings: true

  duplication:
    enabled: true

  structure:
    enabled: true

exclude_patterns:
  - "dist/"
  - "tmp/"
