engines:
  eslint:
    enabled: true
    channel: "eslint-4"
    config:
      config: .eslintrc.js

  duplication:
    enabled: true

  structure:
    enabled: true

  ratings:
    paths:
    - app/**/*
    - config/**/*
    - tests/**/*
    - mirage/**/*
